//
// File generated by HDevelop for HALCON/.NET (C#) Version 13.0.3
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using System.Windows.Forms;
using HalconDotNet;

public partial class HDevelopExport
{
  public HTuple hv_ExpDefaultWinHandle;

  public void HDevelopStop()
  {
    MessageBox.Show("Press button to continue", "Program stop");
  }

  // Procedures 
  // Local procedures 
  public void LoadPars1 (HTuple hv_pathfile, HTuple hv_SetDefault, out HTuple hv_GNDamin, 
      out HTuple hv_fwmhw, out HTuple hv_parop, out HTuple hv_gap, out HTuple hv_jrad, 
      out HTuple hv_groundpn, out HTuple hv_groundgval, out HTuple hv_sm_factor, out HTuple hv_lookaround, 
      out HTuple hv_wpl, out HTuple hv_smoothCADcontours, out HTuple hv_maxdirSP, 
      out HTuple hv_wFWM, out HTuple hv_wside, out HTuple hv_wFWMS, out HTuple hv_wsideS, 
      out HTuple hv_eradMSe, out HTuple hv_eradNFWMremove, out HTuple hv_elengthend, 
      out HTuple hv_elengthnoend, out HTuple hv_jpadd, out HTuple hv_removeGNDfromFWM, 
      out HTuple hv_cutendMSS, out HTuple hv_minWGS, out HTuple hv_minWG, out HTuple hv_useODB, 
      out HTuple hv_autowidth, out HTuple hv_EPexp, out HTuple hv_elongLG, out HTuple hv_TeachPars)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_FileHandleIn = new HTuple(), hv_SerializedItemHandle1 = new HTuple();
    HTuple hv_TeachParsIn = new HTuple(), hv_i = new HTuple();
    // Initialize local and output iconic variables 
    hv_GNDamin = new HTuple();
    hv_fwmhw = new HTuple();
    hv_parop = new HTuple();
    hv_gap = new HTuple();
    hv_jrad = new HTuple();
    hv_groundpn = new HTuple();
    hv_groundgval = new HTuple();
    hv_sm_factor = new HTuple();
    hv_lookaround = new HTuple();
    hv_wpl = new HTuple();
    hv_smoothCADcontours = new HTuple();
    hv_maxdirSP = new HTuple();
    hv_wFWM = new HTuple();
    hv_wside = new HTuple();
    hv_wFWMS = new HTuple();
    hv_wsideS = new HTuple();
    hv_eradMSe = new HTuple();
    hv_eradNFWMremove = new HTuple();
    hv_elengthend = new HTuple();
    hv_elengthnoend = new HTuple();
    hv_jpadd = new HTuple();
    hv_removeGNDfromFWM = new HTuple();
    hv_cutendMSS = new HTuple();
    hv_minWGS = new HTuple();
    hv_minWG = new HTuple();
    hv_useODB = new HTuple();
    hv_autowidth = new HTuple();
    hv_EPexp = new HTuple();
    hv_elongLG = new HTuple();
    hv_TeachPars = new HTuple();
    //*************************************
    //**** Teaching deserialization   *****
    //*************************************
    if ((int)(new HTuple(hv_SetDefault.TupleEqual(1))) != 0)
    {
      hv_GNDamin = 410000;
      hv_fwmhw = 12.5;
      hv_parop = 2.5;
      //*** for skeletons *******
      hv_gap = 1;
      hv_jrad = 10;

      hv_groundpn = 1;
      //groundpn := TeachPars[0]

      hv_groundgval = 3;
      hv_sm_factor = 7;
      hv_lookaround = 7;
      hv_wpl = 15.5;
      hv_smoothCADcontours = 1;
      hv_maxdirSP = 40;
      hv_wFWM = new HTuple();
      hv_wFWM[0] = 30;
      hv_wFWM[1] = 40;
      hv_wside = 5;
      hv_wFWMS = new HTuple();
      hv_wFWMS[0] = 20;
      hv_wFWMS[1] = 31;
      hv_wsideS = 3;
      hv_eradMSe = 9;
      hv_eradNFWMremove = 9;
      hv_elengthend = -1;
      hv_elengthnoend = -25;
      hv_jpadd = 3;
      hv_removeGNDfromFWM = 0;
      hv_cutendMSS = 25;
      hv_minWGS = 3;
      hv_minWG = 4;
      hv_useODB = 0;
      hv_autowidth = 1;
      hv_EPexp = 5;
      hv_elongLG = 10;
    }
    else
    {
      HOperatorSet.OpenFile(hv_pathfile, "input_binary", out hv_FileHandleIn);
      HOperatorSet.FreadSerializedItem(hv_FileHandleIn, out hv_SerializedItemHandle1);
      HOperatorSet.DeserializeTuple(hv_SerializedItemHandle1, out hv_TeachParsIn);
      HOperatorSet.CloseFile(hv_FileHandleIn);
      //tuple_equal (TeachParsIn, TeachParsOut, equal)
      //stop ()

      hv_TeachPars = hv_TeachParsIn.Clone();
      hv_i = 0;
      hv_GNDamin = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_fwmhw = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_parop = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      //*** for skeletons *******
      hv_jrad = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;

      hv_gap = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;

      hv_groundpn = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_groundgval = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_sm_factor = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_lookaround = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_wpl = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_smoothCADcontours = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_maxdirSP = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_wFWM = new HTuple();
      hv_wFWM = hv_wFWM.TupleConcat(hv_TeachPars.TupleSelect(
          hv_i));
      hv_wFWM = hv_wFWM.TupleConcat(hv_TeachPars.TupleSelect(hv_i+1));
      hv_i = hv_i+2;
      hv_wside = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_wFWMS = new HTuple();
      hv_wFWMS = hv_wFWMS.TupleConcat(hv_TeachPars.TupleSelect(
          hv_i));
      hv_wFWMS = hv_wFWMS.TupleConcat(hv_TeachPars.TupleSelect(
          hv_i+1));
      hv_i = hv_i+2;
      hv_wsideS = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_eradMSe = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_eradNFWMremove = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_elengthend = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_elengthnoend = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_jpadd = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_removeGNDfromFWM = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_cutendMSS = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_minWGS = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_minWG = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_useODB = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_autowidth = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_EPexp = hv_TeachPars.TupleSelect(hv_i);
      hv_i = hv_i+1;
      hv_elongLG = hv_TeachPars.TupleSelect(hv_i);
    }


    //**********************************

    return;
  }

  public void MakeandSavePars1 (HTuple hv_pathfile, out HTuple hv_TeachParsOut)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GNDamin = null, hv_fwmhw = null;
    HTuple hv_parop = null, hv_gap = null, hv_jrad = null;
    HTuple hv_groundpn = null, hv_groundgval = null, hv_sm_factor = null;
    HTuple hv_lookaround = null, hv_wpl = null, hv_smoothCADcontours = null;
    HTuple hv_maxdirSP = null, hv_wFWM = null, hv_wside = null;
    HTuple hv_wFWMS = null, hv_wsideS = null, hv_eradMSe = null;
    HTuple hv_eradNFWMremove = null, hv_elengthend = null;
    HTuple hv_elengthnoend = null, hv_jpadd = null, hv_removeGNDfromFWM = null;
    HTuple hv_cutendMSS = null, hv_minWGS = null, hv_minWG = null;
    HTuple hv_useODB = null, hv_autowidth = null, hv_EPexp = null;
    HTuple hv_elongLG = null, hv_SerializedItemHandle = null;
    HTuple hv_FileHandle = null;
    // Initialize local and output iconic variables 
    //*************************************
    //**** Teaching Parameters setting ****
    //*************************************
    hv_GNDamin = 410000;
    hv_fwmhw = 12.5;
    hv_parop = 2.5;
    //*** for skeletons *******
    hv_gap = 1;
    hv_jrad = 10;

    hv_groundpn = 1;
    //groundpn := TeachPars[0]

    hv_groundgval = 3;
    hv_sm_factor = 7;
    hv_lookaround = 7;
    hv_wpl = 15.5;
    hv_smoothCADcontours = 1;
    hv_maxdirSP = 40;
    hv_wFWM = new HTuple();
    hv_wFWM[0] = 30;
    hv_wFWM[1] = 40;
    hv_wside = 5;
    hv_wFWMS = new HTuple();
    hv_wFWMS[0] = 20;
    hv_wFWMS[1] = 31;
    hv_wsideS = 3;
    hv_eradMSe = 9;
    hv_eradNFWMremove = 9;
    hv_elengthend = -1;
    hv_elengthnoend = -25;
    hv_jpadd = 3;
    hv_removeGNDfromFWM = 0;
    hv_cutendMSS = 25;
    hv_minWGS = 3;
    hv_minWG = 4;
    hv_useODB = 0;
    hv_autowidth = 1;
    hv_EPexp = 5;
    hv_elongLG = 10;
    //**********************************
    hv_TeachParsOut = new HTuple();
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_GNDamin);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_fwmhw);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_parop);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_jrad);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_gap);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_groundpn);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_groundgval);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_sm_factor);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_lookaround);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wpl);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_smoothCADcontours);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_maxdirSP);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wFWM);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wside);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wFWMS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wsideS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_eradMSe);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_eradNFWMremove);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elengthend);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elengthnoend);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_jpadd);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_removeGNDfromFWM);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_cutendMSS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_minWGS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_minWG);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_useODB);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_autowidth);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_EPexp);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elongLG);
    HOperatorSet.SerializeTuple(hv_TeachParsOut, out hv_SerializedItemHandle);
    //fileser := pathfile+'/Teach/TeachPars.ser'
    HOperatorSet.OpenFile(hv_pathfile, "output_binary", out hv_FileHandle);
    HOperatorSet.FwriteSerializedItem(hv_FileHandle, hv_SerializedItemHandle);
    HOperatorSet.CloseFile(hv_FileHandle);

    return;
  }

  public void SavePars1 (HTuple hv_pathfile, HTuple hv_GNDamin, HTuple hv_fwmhw, 
      HTuple hv_parop, HTuple hv_jrad, HTuple hv_gap, HTuple hv_groundpn, HTuple hv_groundgval, 
      HTuple hv_sm_factor, HTuple hv_lookaround, HTuple hv_wpl, HTuple hv_smoothCADcontours, 
      HTuple hv_maxdirSP, HTuple hv_wFWM, HTuple hv_wside, HTuple hv_wFWMS, HTuple hv_wsideS, 
      HTuple hv_eradMSe, HTuple hv_eradNFWMremove, HTuple hv_elengthend, HTuple hv_elengthnoend, 
      HTuple hv_jpadd, HTuple hv_removeGNDfromFWM, HTuple hv_cutendMSS, HTuple hv_minWGS, 
      HTuple hv_minWG, HTuple hv_useODB, HTuple hv_autowidth, HTuple hv_EPexp, HTuple hv_elongLG, 
      out HTuple hv_TeachParsOut)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_SerializedItemHandle = null, hv_FileHandle = null;
    // Initialize local and output iconic variables 
    //*************************************
    //**** Teaching Parameters setting ****
    //*************************************
    hv_TeachParsOut = new HTuple();
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_GNDamin);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_fwmhw);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_parop);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_jrad);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_gap);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_groundpn);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_groundgval);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_sm_factor);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_lookaround);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wpl);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_smoothCADcontours);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_maxdirSP);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wFWM);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wside);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wFWMS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_wsideS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_eradMSe);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_eradNFWMremove);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elengthend);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elengthnoend);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_jpadd);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_removeGNDfromFWM);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_cutendMSS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_minWGS);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_minWG);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_useODB);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_autowidth);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_EPexp);
    hv_TeachParsOut = hv_TeachParsOut.TupleConcat(hv_elongLG);
    HOperatorSet.SerializeTuple(hv_TeachParsOut, out hv_SerializedItemHandle);
    //fileser := pathfile+'/Teach/TeachPars.ser'
    HOperatorSet.OpenFile(hv_pathfile, "output_binary", out hv_FileHandle);
    HOperatorSet.FwriteSerializedItem(hv_FileHandle, hv_SerializedItemHandle);
    HOperatorSet.CloseFile(hv_FileHandle);

    return;
  }

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    // Local control variables 

    HTuple hv_path = null, hv_pathfile = null;
    HTuple hv_SetDefault = null, hv_GNDamin = null, hv_fwmhw = null;
    HTuple hv_parop = null, hv_gap = null, hv_jrad = null;
    HTuple hv_groundpn = null, hv_groundgval = null, hv_sm_factor = null;
    HTuple hv_lookaround = null, hv_wpl = null, hv_smoothCADcontours = null;
    HTuple hv_maxdirSP = null, hv_wFWM = null, hv_wside = null;
    HTuple hv_wFWMS = null, hv_wsideS = null, hv_eradMSe = null;
    HTuple hv_eradNFWMremove = null, hv_elengthend = null;
    HTuple hv_elengthnoend = null, hv_jpadd = null, hv_removeGNDfromFWM = null;
    HTuple hv_cutendMSS = null, hv_minWGS = null, hv_minWG = null;
    HTuple hv_useODB = null, hv_autowidth = null, hv_EPexp = null;
    HTuple hv_elongLG = null, hv_TeachPars1 = null, hv_TeachParsOut = null;
    // Initialize local and output iconic variables 
    //*************************************
    //**** Teaching serialization     *****
    //*************************************
    //path := 'D:/240719/p2108-012m2_LayerL1-SHORT3.1-0200/Model/'
    hv_path = "G:/SAMSUNG/Image/p2108-012m2/Model/";
    hv_pathfile = hv_path+"/Teach/TeachPars.ser";
    //*************************************
    //MakeandSavePars1 (pathfile, TeachParsOut1)
    hv_SetDefault = 1;
    LoadPars1(hv_pathfile, hv_SetDefault, out hv_GNDamin, out hv_fwmhw, out hv_parop, 
        out hv_gap, out hv_jrad, out hv_groundpn, out hv_groundgval, out hv_sm_factor, 
        out hv_lookaround, out hv_wpl, out hv_smoothCADcontours, out hv_maxdirSP, 
        out hv_wFWM, out hv_wside, out hv_wFWMS, out hv_wsideS, out hv_eradMSe, out hv_eradNFWMremove, 
        out hv_elengthend, out hv_elengthnoend, out hv_jpadd, out hv_removeGNDfromFWM, 
        out hv_cutendMSS, out hv_minWGS, out hv_minWG, out hv_useODB, out hv_autowidth, 
        out hv_EPexp, out hv_elongLG, out hv_TeachPars1);


    SavePars1(hv_pathfile, hv_GNDamin, hv_fwmhw, hv_parop, hv_jrad, hv_gap, hv_groundpn, 
        hv_groundgval, hv_sm_factor, hv_lookaround, hv_wpl, hv_smoothCADcontours, 
        hv_maxdirSP, hv_wFWM, hv_wside, hv_wFWMS, hv_wsideS, hv_eradMSe, hv_eradNFWMremove, 
        hv_elengthend, hv_elengthnoend, hv_jpadd, hv_removeGNDfromFWM, hv_cutendMSS, 
        hv_minWGS, hv_minWG, hv_useODB, hv_autowidth, hv_EPexp, hv_elongLG, out hv_TeachParsOut);

    HDevelopStop();

    hv_SetDefault = 0;
    LoadPars1(hv_pathfile, hv_SetDefault, out hv_GNDamin, out hv_fwmhw, out hv_parop, 
        out hv_gap, out hv_jrad, out hv_groundpn, out hv_groundgval, out hv_sm_factor, 
        out hv_lookaround, out hv_wpl, out hv_smoothCADcontours, out hv_maxdirSP, 
        out hv_wFWM, out hv_wside, out hv_wFWMS, out hv_wsideS, out hv_eradMSe, out hv_eradNFWMremove, 
        out hv_elengthend, out hv_elengthnoend, out hv_jpadd, out hv_removeGNDfromFWM, 
        out hv_cutendMSS, out hv_minWGS, out hv_minWG, out hv_useODB, out hv_autowidth, 
        out hv_EPexp, out hv_elongLG, out hv_TeachPars1);

    HDevelopStop();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

