//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// InspectTesting.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INSPECT_TESTING_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PARAMS               130
#define IDC_BUTTON_SET_TEACH_FOLDER     1000
#define IDC_BUTTON_CONVERT_TO_BIN       1001
#define IDC_EDIT_FOLDER_TEACH           1002
#define IDC_BUTTON_LOAD_TEACH           1003
#define IDC_BUTTON_SET_DATA_FOLDER      1004
#define IDC_EDIT_FOLDER_DATA            1005
#define IDC_BUTTON_SET_IMAGE            1006
#define IDC_EDIT_IMAGE                  1007
#define IDC_BUTTON4                     1008
#define IDC_BUTTON_INSPECTION_ALL       1008
#define IDC_BUTTON_ALIGNMENT            1009
#define IDC_BUTTON_CONVERT_TO_BIN3      1010
#define IDC_BUTTON_OPEN_SHORT           1010
#define IDC_BUTTON_PINHOLE_ISLAND       1011
#define IDC_BUTTON_CONVERT_TO_BIN5      1012
#define IDC_BUTTON_BUILD_IRB            1012
#define IDC_BUTTON_CONVERT_TO_BIN6      1013
#define IDC_BUTTON_BUILD_FWM            1013
#define IDC_CHECK_RAW_IMAGE             1014
#define IDC_BUTTON_INSPECTION_INIT      1015
#define IDC_BUTTON_READ_IRB             1016
#define IDC_BUTTON_BUILD_FWM2           1016
#define IDC_BUTTON_MAXMIN               1016
#define IDC_BUTTON_BUILD_FWMS           1017
#define IDC_EDIT1                       1018
#define IDC_EDITPRCMBS                  1018
#define IDC_MIN_AREA_OPEN               1018
#define IDC_VIEWIRBP                    1019
#define IDC_GRAY_GAP_OPEN               1019
#define IDC_CHECK_RAW_IMAGE2            1020
#define IDC_CHECK_INIT_AUTO             1020
#define IDC_MIN_AREA_SHORT              1020
#define IDC_VIEWIRBS                    1021
#define IDC_GRAY_GAP_SHORT              1021
#define IDC_VIEWIM                      1022
#define IDC_EDITPRCMBS2                 1023
#define IDC_EDITPRCSPS                  1023
#define IDC_EDITPRCMBS3                 1024
#define IDC_EDITTHR                     1024
#define IDC_BUTTON_LOAD_PARAMS          1025
#define IDC_BUTTON_SAVE_PARAMS          1026
#define IDC_BUTTON_LOW_GRAY             1027
#define IDC_BUTTON_ALIGNMENT2           1028
#define IDC_BUTTON_AUTO_THR             1028
#define IDC_BUTTON_INSPECTION_ALL2      1029
#define IDC_VIEWIRBP2                   1030
#define IDC_VIEWINOD                    1030
#define IDC_EDITPRCMBP                  1031
#define IDC_EDITPRCSPP                  1032
#define IDC_BUTTON_INSPECTION_INIT2     1033
#define IDC_BUTTON_READ_IMAGE           1033
#define IDC_CHECK_AUTOTHR               1034
#define IDC_EDITPRCMBP2                 1035
#define IDC_VIEWIM2                     1035
#define IDC_VIEWIMMOD                   1035
#define IDC_EDITMINABS                  1036
#define IDC_BUTTON_SAVE_PARAMS2         1037
#define IDC_BUTTON_EDIT_PARAMS          1037
#define IDC_EDITMINABS2                 1038
#define IDC_BUTTON1                     1039
#define IDC_BUTTON_SAVE_DEFECTS         1039
#define IDC_BUT_OPEN_SHORT_AUTO         1039
#define IDC_VIEWINOD2                   1040
#define IDC_VIEWSKELG                   1040
#define IDC_BUTTON_BATH_NEXT            1041
#define IDC_BUTTON_BATH_START           1042
#define IDC_EDIT_INSPECTION_UNIT        1043
#define IDC_BUTTON_BATH_STOP            1044
#define IDC_PROGRESS                    1045
#define IDC_CHECK_DEFECT_FOUND_STOP     1046
#define IDC_BUTTON_BATH_PREVIOUS        1047
#define IDC_CHECK_INSPECT_LG            1048
#define IDC_CHECK_INSPECT_FWM           1049
#define IDC_BUTTON_BATH_INIT            1050
#define IDC_CHECK_INSPECT_FWMS          1051
#define IDC_EDIT_INSPECTION_POS         1052
#define IDC_EDIT_INSPECTION_COUNT       1053
#define IDC_LIST_DEFECTS                1054
#define IDC_BUTTON_BATH_NEXT2           1055
#define IDC_BUTTON_BATH_CLEAR           1055
#define IDC_BUTTON_BUILD_FWMS2          1056
#define IDC_BUTTON_MING                 1056
#define IDC_EDIT_INSPECTION_FROM        1056
#define IDC_CHECK_AUTO_THR_BATH         1057
#define IDC_EDIT_DEFECTS_COUNT          1058
#define IDC_IMAGE                       1059
#define IDC_BUTTON2                     1060
#define IDC_BUTTON_FIT                  1060
#define IDC_CHECK_AUTOTHR2              1060
#define IDC_CHECK_MMATOFF               1060
#define IDC_EDITMMATS                   1061
#define IDC_BUTTON3                     1061
#define IDC_CHECK_SAVE_DEFECTS          1062
#define IDC_EDITMID                     1062
#define IDC_BUTTON5                     1063
#define IDC_EDITMARGIN                  1064
#define IDC_CHECK_DISP_DEFECTS          1065
#define IDC_CHECK_UNION_DEFECTS         1066
#define IDC_EDIT_LG_PRC_P               1067
#define IDC_STATICMBP                   1068
#define IDC_STATICSPS                   1069
#define IDC_STATICMBS                   1070
#define IDC_STATIC4                     1071
#define IDC_BUTTON6                     1072
#define IDC_BUTTON_READ                 1072
#define IDC_EDIT_INSPECTION_COUNT3      1073
#define IDC_EDIT_INSPECTION_TO          1073
#define IDC_BUTTON7                     1074
#define IDC_VIEWSKELG2                  1075
#define IDC_BUT_TEACH_OPENSHORT2        1076
#define IDC_BUTTON_OPEN_SHORT2          1077
#define IDC_CHECK_AUTOTHR3              1077
#define IDC_CHECK1                      1078
#define IDC_CHECK_OP2                   1078
#define IDC_STATICSPP                   1079
#define IDC_BUTTON8                     1080
#define IDC_EDITLGPRC2                  1081
#define IDC_EDIT_LG_PRC_S               1081
#define IDC_STATIC5                     1082
#define IDC_EDITSZP                     1083
#define IDC_STATICSPP2                  1084
#define IDC_EDITSZS                     1085
#define IDC_STATICSPP3                  1086
#define IDC_EDITSZP2                    1087
#define IDC_EDITMINWP                   1087
#define IDC_STATICSPP4                  1088
#define IDC_STATICSPABS                 1088
#define IDC_STATICPABS                  1088
#define IDC_EDIT_LG_SZW_P               1089
#define IDC_EDITLGPRC4                  1090
#define IDC_EDIT_LG_AVG_P               1090
#define IDC_EDIT_LG_SZW_S               1091
#define IDC_CHECK_PREPROC               1092
#define IDC_EDIT2                       1093
#define IDC_EDITPRK                     1093
#define IDC_LIST_UNIT_DEFECTS           1094
#define IDC_LIST2                       1095
#define IDC_LIST_DEFECT_ATTRIBUTE       1095
#define IDC_STATICSPP5                  1096
#define IDC_EDITNARWP                   1097
#define IDC_VIEWREGIONG                 1098
#define IDC_STATICNWS                   1099
#define IDC_BUTTON_PARAMS_DLG           1100
#define IDC_VIEWREGIONCUT               1101
#define IDC_TAB1                        1101
#define IDC_STATICSPP6                  1102
#define IDC_EDITWIDEWP                  1103
#define IDC_STATICSPP7                  1104
#define IDC_CHECK_ALIG2                 1104
#define IDC_EDITWIDEWP2                 1105
#define IDC_BUTTON_PROC_CBM_MEANDER     1105
#define IDC_STDWP                       1106
#define IDC_BUTTON9                     1106
#define IDC_BUTTON_PROC_CBM_PAD         1106
#define IDC_EDIT_ABSMB_MEANDER          1107
#define IDC_EDIT_ABSSP_MEANDER          1108
#define IDC_EDIT_RMSIZE_MEANDER         1109
#define IDC_EDIT_ABSMB_PAD              1110
#define IDC_EDIT_ABSSP_PAD              1111
#define IDC_EDIT_RMSIZE_PAD             1112
#define IDC_BUTTON_PROC_CBM_CONN_PAD    1113
#define IDC_EDIT_ABSMB_CONN_PAD         1114
#define IDC_EDIT_ABSSP_CONN_PAD         1115
#define IDC_EDIT_RMSIZE_CONN_PAD        1116
#define IDC_EDIT_CBM_MEANDER            1117
#define IDC_EDIT_CBM_PAD                1118
#define IDC_EDIT_CBM_CONN_PAD           1119
#define IDC_VIEW_CBM_MEANDER            1120
#define IDC_VIEW_CBM_PAD                1121
#define IDC_VIEW_CBM_CONN_PAD           1122
#define IDC_EDIT_ABSMB_WIRE_ANGLE       1123
#define IDC_EDIT_ABSSP_WIRE_ANGLE       1124
#define IDC_EDIT_RMSIZE_WIRE_ANGLE      1125
#define IDC_BUTTON_PROC_CBM_WIRE_ANGLE  1126
#define IDC_EDIT_CBM_WIRE_ANGLE         1127
#define IDC_VIEW_CBM_CONN_PAD2          1128
#define IDC_VIEW_CBM_WIRE_ANGLE         1128
#define IDC_BUT_UPDATE                  2060
#define IDC_EDITMABS                    11035
#define IDC_WPSET                       11106
#define IDC_VIEWREGIONI                 11107
#define IDC_WPSET2                      11108
#define IDC_WPSETI                      11108
#define ID_WIZFINISH2                   12326
#define ID_WIZFINISH3                   12327
#define ID_WIZFINISH4                   12328

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
